#!/bin/bash

curl -sS -X 'POST' \
  'http://customersettingservice-dev.restaurant365.com/Setting' \
  -H 'accept: application/json' \
  -H "X-R365-Customer-Id: ${1}" \
  -H 'Content-Type: application/json' \
  -d '[ 1,2,3,4,5,6 ]' | jq 'map({(.settingId): .value}) | add'

